name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
version-template: $MAJOR.$MINOR.$PATCH
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "feat"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: 📝 Documentation updates
    labels:
      - "documentation"
      - "doc"
  - title: 🚦 Tests
    labels:
      - "test"
      - "tests"
change-template: "- $TITLE @$AUTHOR $BODY"
change-title-escapes: '\<*_&'
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
autolabeler:
  - label: 'documentation'
    branch:
      - '/doc\/.+/'
    title:
      - '/^doc/i'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
      - '/bug\/.+/'
    title:
      - '/^fix/i'
      - '/^bug/i'
  - label: 'feature'
    branch:
      - '/feature\/.+/'
      - '/feat\/.+/'
    title:
      - '/^feature/i'
      - '/^feat/i'
  - label: 'chore'
    branch:
      - '/chore\/.+/'
    title:
      - '/^chore/i'
  - label: 'test'
    branch:
      - '/test\/.+/'
    title:
      - '/^test/i'
template: |
  ## Changes

  $CHANGES
