name: preda-release
on:
  push:
    branches: [main]
jobs:
  package:
    name: Package PREDA
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: npm install, build and test
        run: |
          yarn install --registry https://registry.npmmirror.com/
          cd web 
          yarn install --registry https://registry.npmmirror.com/
          cd -
          npm run compile --if-present

      - name: make tag and update change.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npx standard-version

      - name: clear local
        run: |
          rm -rf out/*

      - name: package with vsce
        run: |
          yarn global add vsce
          vsce package

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: upload a build artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: preda-${{ steps.package-version.outputs.current-version }}
          path: ./*.vsix

      - name: committer
        run: |
          git push --follow-tags origin main

      - uses: release-drafter/release-drafter@v5
        id: drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload vsix
        id: upload-vsix
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./*.vsix
          asset_name: preda-${{ steps.package-version.outputs.current-version }}.vsix
          asset_content_type: application/zip
