name: preda-release
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  package:
    name: Package PREDA
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: setup node.jobs
        uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: npm install, build and test
        run: |
          yarn install --registry https://registry.npmmirror.com/
          cd web 
          yarn install --registry https://registry.npmmirror.com/
          cd -
          npm run build --if-present
          npm test --if-present

      - name: make tag and update change.log
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          npx standard-version

      - name: clear local
        run: |
          rm -rf out/*

      - name: package with vsce
        run: |
          yarn global add vsce
          vsce package

      - name: upload a build artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: preda
          path: ./*.vsix
     
      - name: committer
        run: |
          git push --follow-tags origin main
          
  update_release_draft:
      needs: [package]
      permissions:
        # write permission is required to create a github release
        contents: write
        # write permission is required for autolabeler
        # otherwise, read permission is required at least
        pull-requests: write
      runs-on: ubuntu-latest
      steps:
        # (Optional) GitHub Enterprise requires GHE_HOST variable set
        #- name: Set GHE_HOST
        #  run: |
        #    echo "GHE_HOST=${GITHUB_SERVER_URL##https:\/\/}" >> $GITHUB_ENV

        # Drafts your next Release notes as Pull Requests are merged into "master"
        - uses: release-drafter/release-drafter@v5
          # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
          # with:
          #   config-name: my-config.yml
          #   disable-autolabeler: true
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
